MARGINAL_COST = 1.0
MONOPOLY_PRICE = 2.0
COMPETITIVE_PRICE = 1.0
NUM_PRICE_LEVELS = 15

NUM_ROUNDS = 1000
NUM_RUNS = 5
RANDOM_SEED = 42

QL_ALPHA = 0.15
QL_GAMMA = 0.95
QL_EPSILON_START = 1.0
QL_EPSILON_END = 0.01
QL_EPSILON_DECAY = 0.995

LLM_MODEL = "llama3.2:3b"
LLM_HISTORY_WINDOW = 10
LLM_MAX_TOKENS = 64
LLM_ROUNDS = 200

GREEDY_UNDERCUT= 0.05

DATA_DIR = "data"
RESULTS_FILE = "data/results.csv"
ROUNDS_FILE = "data/round_by_round.csv"